/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdea5",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "on-background": "#121414",
        "inverse-surface": "#121414",
        "primary-container": "#c5a059",
        "inverse-primary": "#775a19",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary": "#303030",
        "background": "#ffffff",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-error-container": "#ffdad6",
        "surface": "#ffffff",
        "surface-container-high": "#ededed",
        "secondary-fixed": "#e5e2e1",
        "surface-container-low": "#f9f9f9",
        "on-secondary-container": "#bab8b7",
        "surface-bright": "#ffffff",
        "surface-dim": "#f5f5f5",
        "tertiary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#e9c176",
        "on-primary-container": "#4e3700",
        "tertiary": "#c6c6c6",
        "on-error": "#690005",
        "on-surface": "#121414",
        "outline": "#7a7a7a",
        "on-tertiary-fixed": "#1b1b1b",
        "on-primary-fixed": "#261900",
        "on-primary-fixed-variant": "#5d4201",
        "on-surface-variant": "#4a4a4a",
        "surface-container": "#f5f5f5",
        "surface-tint": "#e9c176",
        "tertiary-container": "#a5a5a5",
        "secondary-container": "#4a4949",
        "secondary-fixed-dim": "#c8c6c5",
        "outline-variant": "#d1d1d1",
        "on-secondary-fixed-variant": "#474646",
        "surface-container-highest": "#e0e0e0",
        "inverse-on-surface": "#ffffff",
        "primary": "#9a732a",
        "on-secondary": "#313030",
        "secondary": "#c8c6c5",
        "on-tertiary-fixed-variant": "#474747",
        "on-tertiary-container": "#3b3b3b",
        "surface-variant": "#e0e0e0",
        "brand-gold": "#8e6624",
        "brand-dark": "#ffffff",
        "brand-surface": "#f9f9f9",
        "brand-text": "#1a1b1b",
        "brand-muted": "#666666"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin": "64px",
        "stack-sm": "12px",
        "section-gap": "128px",
        "stack-md": "24px",
        "gutter": "24px",
        "unit": "4px"
      },
      fontFamily: {
        "headline-sm": ["Noto Serif", "serif"],
        "headline-md": ["Noto Serif", "serif"],
        "display-lg": ["Noto Serif", "serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "serif": ["Noto Serif", "serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "headline-md": ["48px", { lineHeight: "1.2", fontWeight: "400" }],
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.2em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
